apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
    labels:
      run: jgrp
    name: jgrp
  spec:
    replicas: 5
    template:
      metadata:
        labels:
          run: jgrp
          deploymentConfig: jgrp
      spec:
        containers:
        - image: belaban/jgroups
          command: ["chat.sh"]
          args: ["-props dns-ping.xml -o"]
 #         command: ["/bin/sh","-c"]
 #         args: ["{ (sleep 50; touch /opt/jgroups/ready)& } ; chat.sh -props dns-ping.xml -o"]
          env:
            - name: DNS_QUERY
              value: jgrp
          name: jgrp
#          readinessProbe:
#            exec:
#              command:
#              - cat
#              - /opt/jgroups/ready
#            initialDelaySeconds: 10
#            periodSeconds: 5
kind: List
metadata: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: jgrp
  labels:
    run: jgrp
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: ping
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
     deploymentConfig: jgrp
---


