apiVersion: apps/v1
kind: Deployment
metadata:
  name: jgrp2
  labels:
    run: jgrp2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jgrp2
  template:
    metadata:
      labels:
        run: jgrp2
    spec:
      containers:
      - image: belaban/jgroups
        name: jgrp2
        command: ["chat.sh"]
        args: ["-props tcp.xml -o"]
        ports:
          - containerPort: 7900
        env:
          - name: TCP_PORT
            value: "7900"
          - name: TCPPING_PORT_RANGE
            value: "0"
#          - name: JGROUPS_EXTERNAL_ADDR
#            value: "a3d59e22a1b4511eaaac802384b7d669-711219896.us-east-1.elb.amazonaws.com"
          - name: TCPPING_INITIAL_HOSTS
            value: "afbea1a011c0911eaaac802384b7d669-1529495313.us-east-1.elb.amazonaws.com [7800]"


