apiVersion: apps/v1
kind: Deployment
metadata:
  name: jgrp2
  labels:
    run: jgrp2
spec:
  replicas: 2
  selector:
    matchLabels:
      run: jgrp2
  template:
    metadata:
      labels:
        run: jgrp2
    spec:
      containers:
      - image: belaban/jgroups
        name: jgrp2
        command: ["chat.sh"]
        args: ["-props tcp.xml -o"]
        env:
          - name: TCP_PORT
            value: "7850"
          - name: JGROUPS_EXTERNAL_ADDR
            value: "a86e6567e1a7711eaaac802384b7d669-2109456829.us-east-1.elb.amazonaws.com"
          - name: TCPPING_INITIAL_HOSTS
            value: "a82d200fd1a7711ea969e0e2826de564-1047104001.us-east-1.elb.amazonaws.com[7800],a86e6567e1a7711eaaac802384b7d669-2109456829.us-east-1.elb.amazonaws.com[7850]"
