apiVersion: apps/v1
kind: Deployment
metadata:
  name: jgrp
  labels:
    run: jgrp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jgrp
  template:
    metadata:
      labels:
        run: jgrp
    spec:
      containers:
      - image: belaban/jgroups
        name: jgrp
        command: ["chat.sh"]
        args: ["-props tunnel.xml -o"]
        ports:
          - containerPort: 7800
        env:
#          - name: TCP_PORT
#            value: "7800"
#          - name: JGROUPS_EXTERNAL_ADDR
#            value: "afbea1a011c0911eaaac802384b7d669-1529495313.us-east-1.elb.amazonaws.com"
          - name: TCPGOSSIP_INITIAL_HOSTS
            value: "127.0.0.1[12001]"


