apiVersion: apps/v1
kind: Deployment
metadata:
  name: jgrp
  labels:
    run: jgrp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jgrp
  template:
    metadata:
      labels:
        run: jgrp
    spec:
      containers:
      - image: belaban/jgroups
        name: jgrp
        command: ["chat.sh"]
        args: ["-props tcp.xml -o"]
        env:
          - name: TCP_PORT
            value: "12000"
          - name: TCPPING_PORT_RANGE
            value: "0"
#          - name: JGROUPS_EXTERNAL_ADDR
#            value: "a3d59e22a1b4511eaaac802384b7d669-711219896.us-east-1.elb.amazonaws.com"
          - name: TCPPING_INITIAL_HOSTS
            value: "a3d59e22a1b4511eaaac802384b7d669-711219896.us-east-1.elb.amazonaws.com[12000]"


