apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  name: lb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 12000
      name: echo-server
      protocol: TCP
    - port: 7800
      name: jgroups
      protocol: TCP
  selector:
    run: jgrp
