apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfc
  labels:
    site: sfc
spec:
  replicas: 1
  selector:
    matchLabels:
      site: sfc
  template:
    metadata:
      labels:
        site: sfc
    spec:
      containers:
      - image: belaban/jgroups
        name: sfc
        command: ["chat.sh"]
        args: ["-props sfc.xml -o"]
        ports:
          - containerPort: 7800
        env:
#          - name: TCP_PORT
#            value: "7800"
#          - name: JGROUPS_EXTERNAL_ADDR
#            value: "afbea1a011c0911eaaac802384b7d669-1529495313.us-east-1.elb.amazonaws.com"
          - name: DNS_QUERY
            value: sfc
          - name: TUNNEL_INITIAL_HOSTS
            value: "a618ec546257011eab7290e939514b67-695e802f565187e4.elb.us-east-1.amazonaws.com[12001],a9692b520257211eaa10b0e07ddc8c1f-aa89107390748962.elb.us-west-2.amazonaws.com[12001]"
---
apiVersion: v1
kind: Service
metadata:
  name: sfc
  labels:
    site: sfc
spec:
  clusterIP: None
  ports:
    - name: jgroups
      port: 7800
      protocol: TCP
      targetPort: 7800
    - name: debug
      port: 8787
      protocol: TCP
      targetPort: 8787
  selector:
     site: sfc
  sessionAffinity: None
#  type: ClusterIP
  type: ClusterIP
status:
  loadBalancer: {}

